version: "3"
services:
  laravel:
    build:
      context: ./laravel
    volumes:
      - ./laravel/src:/app
      - ./laravel/logs:/var/log/php
      - ./laravel/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME:-laravel_local}
      - DB_USERNAME=${DB_USERNAME:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - TZ=UTC
  nginx:
    image: nginx:1.17-alpine
    depends_on:
      - laravel
    ports:
      - 8080:80
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=UTC

  db:
    image: mysql:5.7
    volumes:
      - db-store:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USERNAME:-laravel}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root_password}
      - TZ=UTC
    ports:
      - "3388:3306"

volumes:
    db-store: